import { RankData } from "src/interfaces";

export const Ranks: RankData[] = [
    {
        type: 'BRONZE',
        direct: 1,
        company: 100,
        income: 25,
        validity: 30,
    },
    {
        type: 'SILVER',
        direct: 1,
        company: 250,
        income: 50,
        validity: 30,
    },
    {
        type: 'GOLD',
        direct: 2,
        company: 500,
        income: 50,
        validity: 40,
    },
    {
        type: 'PLATINUM',
        direct: 2,
        company: 1000,
        income: 100,
        validity: 50,
    },
    {
        type: 'EMERALD',
        direct: 3,
        company: 2500,
        income: 200,
        validity: 50,
    },
    {
        type: 'RUBY',
        direct: 3,
        company: 5000,
        income: 300,
        validity: 50,
    },
    {
        type: 'PEARL',
        direct: 5,
        company: 10000,
        income: 500,
        validity: 60,
    },
    {
        type: "DIAMOND",
        direct: 7,
        company: 25000,
        income: 1000,
        validity: 70,
    },
    {
        type: 'WHITE DIAMOND',
        direct: 10,
        company: 50000,
        income: 1500,
        validity: 70,
    },
    {
        type: 'BLACK DIAMOND',
        direct: 12,
        company: 100000,
        income: 2000,
        validity: 100,
    },
    {
        type: 'BLUE DIAMOND',
        direct: 15,
        company: 250000,
        income: 3000,
        validity: 100,
    },
    {
        type: 'AMBASSADOR',
        direct: 20,
        company: 500000,
        income: 5000,
        validity: 120,
    },
];